# Revision ID: c6035ee33b5d
# Revises:
# Create Date: 2025-12-30 18:22:11.185384
# vsechny tabulky aplikace
from alembic import op
import sqlalchemy as sa


# Identifikatory revize pro Alembic (down_revision=None znamena prvni migrace)
revision = 'c6035ee33b5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user','admin')", name='chk_app_user_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        # Unikatni index na JTI (JWT ID) pro rychle overeni revokace tokenu
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_performed_by'), ['performed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('buddy',
    sa.Column('buddy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('buddy_id')
    )
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buddy_user_id'), ['user_id'], unique=False)

    op.create_table('device',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('firmware', sa.String(length=80), nullable=True),
    sa.Column('battery_v', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hw_model_display', sa.String(length=80), nullable=True),
    sa.Column('bt_mac', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_user_id'), ['user_id'], unique=False)

    op.create_table('diver_profile',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('units', sa.String(length=10), server_default='metric', nullable=True),
    sa.Column('sac_l_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descent_rate_m_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ascent_rate_m_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    with op.batch_alter_table('diver_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diver_profile_user_id'), ['user_id'], unique=True)

    op.create_table('equipment_item',
    sa.Column('equipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('bought_on', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('state', sa.String(length=20), server_default='ok', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('volume_l', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('work_pressure_bar', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('valve', sa.String(length=40), nullable=True),
    sa.Column('material', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    with op.batch_alter_table('equipment_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_item_user_id'), ['user_id'], unique=False)

    op.create_table('etl_export',
    sa.Column('export_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('export_id')
    )
    with op.batch_alter_table('etl_export', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etl_export_user_id'), ['user_id'], unique=False)

    op.create_table('etl_import',
    sa.Column('import_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ok', nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=100), nullable=True),
    sa.Column('raw_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('import_id')
    )
    with op.batch_alter_table('etl_import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etl_import_user_id'), ['user_id'], unique=False)

    op.create_table('gas_mix',
    sa.Column('gas_mix_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gas_type', sa.String(length=20), nullable=False),
    sa.Column('o2_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('he_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    # Rozsahove omezeni pro procenta -- NULL je povoleno (napr. vzduch nema explicitni o2)
    sa.CheckConstraint('(he_percent IS NULL OR (he_percent >= 0 AND he_percent <= 100))', name='chk_he_0_100'),
    sa.CheckConstraint('(o2_percent IS NULL OR (o2_percent >= 0 AND o2_percent <= 100))', name='chk_o2_0_100'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('gas_mix_id'),
    # Unikatni kombinace gas_type + o2 + he pro kazdeho uzivatele (zabrání duplicitam)
    sa.UniqueConstraint('user_id', 'gas_type', 'o2_percent', 'he_percent', name='uq_user_gas_mix')
    )
    with op.batch_alter_table('gas_mix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gas_mix_user_id'), ['user_id'], unique=False)

    op.create_table('license',
    sa.Column('license_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agency', sa.String(length=50), nullable=True),
    sa.Column('certification', sa.String(length=80), nullable=True),
    sa.Column('level', sa.String(length=80), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('license_id')
    )
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_user_id'), ['user_id'], unique=False)

    op.create_table('site',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('body_of_water', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('current', sa.String(length=40), nullable=True),
    sa.Column('access', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('photo_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_user_id'), ['user_id'], unique=False)

    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_tag')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_user_id'), ['user_id'], unique=False)

    op.create_table('tank',
    sa.Column('tank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('volume_l', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('work_pressure_bar', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('material', sa.String(length=40), nullable=True),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('valve', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('tank_id')
    )
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tank_user_id'), ['user_id'], unique=False)

    op.create_table('trip',
    sa.Column('trip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_user_id'), ['user_id'], unique=False)

    op.create_table('unit_prefs',
    # user_id je zaroven PK i FK -- kazdy uzivatel ma nejvyse jeden zaznam preferenci
    sa.Column('user_id', sa.Integer(), nullable=False),
    # data je JSON blob se vsemi preferenci jednotek; vychozi je prazdny objekt
    sa.Column('data', sa.JSON(), server_default='{}', nullable=False),
    # CASCADE DELETE -- preference se odstranuji automaticky pri smazani uzivatele
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dive',
    sa.Column('dive_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('max_depth_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_depth_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('surface_pressure_bar', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('water_temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('air_temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('breathing_system', sa.String(length=20), server_default='open_circuit', nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=True),
    sa.Column('surface_interval_min', sa.Integer(), nullable=True),
    sa.Column('deco_model', sa.String(length=40), nullable=True),
    sa.Column('gf_low', sa.Integer(), nullable=True),
    sa.Column('gf_high', sa.Integer(), nullable=True),
    sa.Column('ndl_min', sa.Integer(), nullable=True),
    sa.Column('cns_max_pct', sa.Integer(), nullable=True),
    sa.Column('otu', sa.Integer(), nullable=True),
    sa.Column('ceiling_max_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_meta_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    # Hloubky a cas nemohou byt zaporné (NULL je povolene -- ponor muze byt rozdelany)
    sa.CheckConstraint('avg_depth_m IS NULL OR avg_depth_m >= 0', name='chk_avg_depth_nonneg'),
    sa.CheckConstraint('duration_min IS NULL OR duration_min >= 0', name='chk_duration_min_nonneg'),
    sa.CheckConstraint('max_depth_m IS NULL OR max_depth_m >= 0', name='chk_max_depth_nonneg'),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['license.license_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.trip_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('dive_id')
    )
    with op.batch_alter_table('dive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dive_user_id'), ['user_id'], unique=False)

    op.create_table('equipment_service',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=80), nullable=True),
    sa.Column('frequency_months', sa.Integer(), nullable=True),
    sa.Column('last_service', sa.Date(), nullable=True),
    sa.Column('next_service', sa.Date(), nullable=True),
    sa.Column('workshop', sa.String(length=120), nullable=True),
    sa.Column('document_url', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_item.equipment_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_dives', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('deepest_m', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('avg_depth_m', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('fav_site_id', sa.Integer(), nullable=True),
    sa.Column('last_dive_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fav_site_id'], ['site.site_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dive_attachment',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('dive_buddy',
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('buddy_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['buddy_id'], ['buddy.buddy_id'], ),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.PrimaryKeyConstraint('dive_id', 'buddy_id')
    )
    op.create_table('dive_equipment',
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('equipment_snapshot_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_item.equipment_id'], ),
    sa.PrimaryKeyConstraint('dive_id', 'equipment_id')
    )
    op.create_table('dive_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('t_min', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('depth_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('dive_segment',
    sa.Column('dive_segment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('start_t_min', sa.Integer(), nullable=False),
    sa.Column('end_t_min', sa.Integer(), nullable=True),
    sa.Column('gas_mix_id', sa.Integer(), nullable=True),
    sa.Column('setpoint_ppO2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.ForeignKeyConstraint(['gas_mix_id'], ['gas_mix.gas_mix_id'], ),
    sa.PrimaryKeyConstraint('dive_segment_id')
    )
    op.create_table('dive_tag',
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('dive_id', 'tag_id')
    )
    op.create_table('dive_tank',
    sa.Column('dive_tank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    # tank_id a gas_mix_id jsou volitelne -- lze zadat jen plyn bez konkretni lahve
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('gas_mix_id', sa.Integer(), nullable=True),
    sa.Column('start_pressure_bar', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('end_pressure_bar', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.ForeignKeyConstraint(['gas_mix_id'], ['gas_mix.gas_mix_id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tank.tank_id'], ),
    sa.PrimaryKeyConstraint('dive_tank_id'),
    # Kazda lahev muze byt na jednom ponoru uvedena nejvyse jednou
    sa.UniqueConstraint('dive_id', 'tank_id', name='uq_dive_tank_once_per_dive')
    )
    op.create_table('exposure_metrics',
    sa.Column('exposure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('cns_start', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cns_end', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('otu_start', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('otu_end', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('max_ppO2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.PrimaryKeyConstraint('exposure_id'),
    sa.UniqueConstraint('dive_id')
    )
    op.create_table('media',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_dive_id'), ['dive_id'], unique=False)

    op.create_table('profile_sample',
    sa.Column('sample_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('t_min', sa.Integer(), nullable=False),
    sa.Column('depth_m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ndl_min', sa.Integer(), nullable=True),
    sa.Column('ceilings_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ascent_rate_mpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tank_pressure_bar', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ppO2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('setpoint_o2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ceiling_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.dive_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    # ### end Alembic commands ###


def downgrade():
    """
    Vraci migrace zpet -- odebira vsechny tabulky v opacnem poradi nez upgrade().
    Nejdrive jsou odebrane tabulky zavisle na FK, naposledy tabulka app_user.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_sample')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_dive_id'))

    op.drop_table('media')
    op.drop_table('exposure_metrics')
    op.drop_table('dive_tank')
    op.drop_table('dive_tag')
    op.drop_table('dive_segment')
    op.drop_table('dive_event')
    op.drop_table('dive_equipment')
    op.drop_table('dive_buddy')
    op.drop_table('dive_attachment')
    op.drop_table('user_stats')
    op.drop_table('equipment_service')
    with op.batch_alter_table('dive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dive_user_id'))

    op.drop_table('dive')
    op.drop_table('unit_prefs')
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_user_id'))

    op.drop_table('trip')
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tank_user_id'))

    op.drop_table('tank')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_user_id'))

    op.drop_table('tag')
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_user_id'))
        batch_op.drop_index(batch_op.f('ix_site_name'))

    op.drop_table('site')
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_user_id'))

    op.drop_table('license')
    with op.batch_alter_table('gas_mix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gas_mix_user_id'))

    op.drop_table('gas_mix')
    with op.batch_alter_table('etl_import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etl_import_user_id'))

    op.drop_table('etl_import')
    with op.batch_alter_table('etl_export', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etl_export_user_id'))

    op.drop_table('etl_export')
    with op.batch_alter_table('equipment_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_item_user_id'))

    op.drop_table('equipment_item')
    with op.batch_alter_table('diver_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diver_profile_user_id'))

    op.drop_table('diver_profile')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_user_id'))

    op.drop_table('device')
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buddy_user_id'))

    op.drop_table('buddy')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_performed_by'))

    op.drop_table('audit_log')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    op.drop_table('app_user')
    # ### end Alembic commands ###
